#!/usr/bin/with-contenv bash

logConsole() {
        fdmove -c 1 2 s6-echo "[$(basename `pwd`)]: $1";
}

logConsole "Setting Up....."
logConsole " "
logConsole "========================================================================"
logConsole "Detailed Logging is available in the logs directory of the mapped volume"
logConsole "========================================================================"
logConsole " "

: "${MQTT_PORT:=1883}"
: "${MQTT_SERVER:=localhost}"
: "${USB_PATH:=/dev/ttyUSB0}"

OZW_ARGS=()
if [[ ! -c $USB_PATH ]]; then
	logConsole "USB Path \"$USB_PATH\" does not exist or is not a Character Device"
	exit -5
fi
OZW_ARGS+=(-s "$USB_PATH")
OZW_ARGS+=(--config-dir "${OZW_CONFIG_DIR:-/opt/ozw/config}")
OZW_ARGS+=(--user-dir "${OZW_USER_DIR:-/opt/ozw/config}")
OZW_ARGS+=(--mqtt-server "$MQTT_SERVER")
OZW_ARGS+=(--mqtt-port "$MQTT_PORT")
if [[ ${STOP_ON_FAILURE:=true} == true ]]; then
	OZW_ARGS+=(--stop-on-failure)
elif [[ $STOP_ON_FAILURE != false ]]; then
	logConsole "Invalid value for STOP_ON_FAILURE: \"$STOP_ON_FAILURE\", expected true or false."
	exit -5
fi
if [[ ${MQTT_TLS:=false} == true ]]; then
	OZW_ARGS+=(--mqtt-tls)
elif [[ $MQTT_TLS != false ]]; then
	logConsole "Invalid value for MQTT_TLS: \"$MQTT_TLS\", expected true or false."
	exit -5
fi
OZW_ARGS+=(--mqtt-instance "${OZW_INSTANCE:-1}")
if [[ -n $MQTT_USERNAME ]]; then
	OZW_ARGS+=(--mqtt-username "$MQTT_USERNAME")
fi

logConsole "Waiting until the MQTT broker at $MQTT_SERVER:$MQTT_PORT is available..."
if ! timeout "${MQTT_CONNECT_TIMEOUT:=30}" \
	bash -c "until echo > /dev/tcp/$MQTT_SERVER/$MQTT_PORT; do sleep 1; done" &>/dev/null
then
	logConsole "Could not connect to the MQTT broker after $MQTT_CONNECT_TIMEOUT seconds"
	exit -3
fi

logConsole "Starting..."
set -- /usr/local/bin/ozwdaemon "${OZW_ARGS[@]}" "$@"
logConsole "Executing: $@"
exec fdmove -c 2 1 "$@"
