#ifndef QTOPENZWAVE_GLOBAL_H
#define QTOPENZWAVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTOPENZWAVE_LIBRARY)
#  define QTOPENZWAVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTOPENZWAVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTOPENZWAVE_GLOBAL_H
